CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'myuserpass';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON product,order TO 'myuser' IDENTIFIED BY 'myuserpass';
FLUSH PRIVILEGES;
